baseURL = "https://emiette.net/"
defaultContentLanguage = 'fr'
languageCode = 'fr-FR'
title = "Émi Lefèvre"
timeZone = 'Europe/Paris'

disableKinds = ["taxonomy", "term"]


[params]
  description = "Site de Émi Lefèvre, gamedev generalist."

[params.social]
  email = 'emi@planetoast.com'
  linkedin = 'https://www.linkedin.com/in/emi-le/'
